### ISSUE TITLE
videogrid does not work. 

### ISSUE THREAD

**Issue by davidppf** [Roxiler/react-fb-image-video-grid#3]
Code in lib/videogrid is imagegrid

**Comment by sai6855** [comment]
It's difficult to identify the isssue with description you have provided, can you provide code snippet on how you are using video grid component?

**Comment by davidppf** [comment]
@sai6855 

As mentioned, the code you put for VideoGRID Component is for ImageComponent. Also, the videogrid example in the readme 
file is also not correct for single video, 


![image](https://user-images.githubusercontent.com/73885623/173609600-a31c7be1-b036-403a-ab62-54cee79b152b.png)

**Comment by davidppf** [comment]
After testing the ImageGrid to video tag, I understand it now.

You change the component name to MediaGrid (which is for both, image and video) then, if the file['type'].include('image') => render img tag, if not, video tag


https://codesandbox.io/s/react-fb-image-video-grid-forked-b6vl70?file=/src/App.js

**Comment by sai6855** [comment]
Thanks for spotting the issue, i'll update the readme.

Yes you are right currently both ImageGrid and VideoGrid uses same code, we have exported as seperate components because in future if we want to add any props which are media specific or even change some of functionality which are specific to either of components we can do it without breaking the existing code.

**Comment by sai6855** [comment]
closing the issue as readme is updated
